import type { LocationOption } from "@/domain/types";

export const AIRPORTS: LocationOption[] = [
  {
    iata: "ATL",
    name: "Hartsfield Jackson Atlanta International",
    city: "Atlanta",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "LAX",
    name: "Los Angeles International",
    city: "Los Angeles",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "ORD",
    name: "O Hare International",
    city: "Chicago",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "DFW",
    name: "Dallas Fort Worth International",
    city: "Dallas",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "DEN",
    name: "Denver International",
    city: "Denver",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "JFK",
    name: "John F Kennedy International",
    city: "New York",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "SFO",
    name: "San Francisco International",
    city: "San Francisco",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "SEA",
    name: "Seattle Tacoma International",
    city: "Seattle",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "LAS",
    name: "Harry Reid International",
    city: "Las Vegas",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "MCO",
    name: "Orlando International",
    city: "Orlando",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "CLT",
    name: "Charlotte Douglas International",
    city: "Charlotte",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "PHX",
    name: "Phoenix Sky Harbor International",
    city: "Phoenix",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "IAH",
    name: "George Bush Intercontinental",
    city: "Houston",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "MIA",
    name: "Miami International",
    city: "Miami",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "BOS",
    name: "Logan International",
    city: "Boston",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "MSP",
    name: "Minneapolis Saint Paul International",
    city: "Minneapolis",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "DTW",
    name: "Detroit Metropolitan Wayne County",
    city: "Detroit",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "PHL",
    name: "Philadelphia International",
    city: "Philadelphia",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "FLL",
    name: "Fort Lauderdale Hollywood International",
    city: "Fort Lauderdale",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "BWI",
    name: "Baltimore Washington International",
    city: "Baltimore",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "SAN",
    name: "San Diego International",
    city: "San Diego",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "TPA",
    name: "Tampa International",
    city: "Tampa",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "PDX",
    name: "Portland International",
    city: "Portland",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "HNL",
    name: "Daniel K Inouye International",
    city: "Honolulu",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "SLC",
    name: "Salt Lake City International",
    city: "Salt Lake City",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "IAD",
    name: "Washington Dulles International",
    city: "Washington",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "DCA",
    name: "Ronald Reagan Washington National",
    city: "Washington",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "RDU",
    name: "Raleigh Durham International",
    city: "Raleigh",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "AUS",
    name: "Austin Bergstrom International",
    city: "Austin",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "BNA",
    name: "Nashville International",
    city: "Nashville",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "MSY",
    name: "Louis Armstrong New Orleans International",
    city: "New Orleans",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "SJC",
    name: "San Jose International",
    city: "San Jose",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "SMF",
    name: "Sacramento International",
    city: "Sacramento",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "OAK",
    name: "Oakland International",
    city: "Oakland",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "MCI",
    name: "Kansas City International",
    city: "Kansas City",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "CLE",
    name: "Cleveland Hopkins International",
    city: "Cleveland",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "PIT",
    name: "Pittsburgh International",
    city: "Pittsburgh",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "CVG",
    name: "Cincinnati Northern Kentucky International",
    city: "Cincinnati",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "STL",
    name: "St Louis Lambert International",
    city: "St Louis",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "IND",
    name: "Indianapolis International",
    city: "Indianapolis",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "RIC",
    name: "Richmond International",
    city: "Richmond",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "JAX",
    name: "Jacksonville International",
    city: "Jacksonville",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "PBI",
    name: "Palm Beach International",
    city: "West Palm Beach",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "SNA",
    name: "John Wayne Airport",
    city: "Santa Ana",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "BUR",
    name: "Hollywood Burbank Airport",
    city: "Burbank",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "LGB",
    name: "Long Beach Airport",
    city: "Long Beach",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "OKC",
    name: "Will Rogers World",
    city: "Oklahoma City",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "ABQ",
    name: "Albuquerque International Sunport",
    city: "Albuquerque",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "TUS",
    name: "Tucson International",
    city: "Tucson",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "ANC",
    name: "Ted Stevens Anchorage International",
    city: "Anchorage",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "SJU",
    name: "Luis Munoz Marin International",
    city: "San Juan",
    country: "Puerto Rico",
    countryCode: "PR",
    subType: "AIRPORT",
  },
  {
    iata: "LGA",
    name: "LaGuardia",
    city: "New York",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "EWR",
    name: "Newark Liberty International",
    city: "Newark",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "SAT",
    name: "San Antonio International",
    city: "San Antonio",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "DAL",
    name: "Dallas Love Field",
    city: "Dallas",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "HOU",
    name: "William P Hobby",
    city: "Houston",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "RNO",
    name: "Reno Tahoe International",
    city: "Reno",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "BOI",
    name: "Boise Airport",
    city: "Boise",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "BUF",
    name: "Buffalo Niagara International",
    city: "Buffalo",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "ALB",
    name: "Albany International",
    city: "Albany",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "PVD",
    name: "Providence T F Green",
    city: "Providence",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "ROC",
    name: "Greater Rochester International",
    city: "Rochester",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "ORF",
    name: "Norfolk International",
    city: "Norfolk",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "CHS",
    name: "Charleston International",
    city: "Charleston",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "SAV",
    name: "Savannah Hilton Head",
    city: "Savannah",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "TUL",
    name: "Tulsa International",
    city: "Tulsa",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "GSP",
    name: "Greenville Spartanburg International",
    city: "Greenville",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "HSV",
    name: "Huntsville International",
    city: "Huntsville",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "ICT",
    name: "Wichita Dwight D Eisenhower National",
    city: "Wichita",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "MKE",
    name: "Milwaukee Mitchell International",
    city: "Milwaukee",
    country: "United States",
    countryCode: "US",
    subType: "AIRPORT",
  },
  {
    iata: "YYZ",
    name: "Toronto Pearson International",
    city: "Toronto",
    country: "Canada",
    countryCode: "CA",
    subType: "AIRPORT",
  },
  {
    iata: "YVR",
    name: "Vancouver International",
    city: "Vancouver",
    country: "Canada",
    countryCode: "CA",
    subType: "AIRPORT",
  },
  {
    iata: "YUL",
    name: "Montreal Trudeau International",
    city: "Montreal",
    country: "Canada",
    countryCode: "CA",
    subType: "AIRPORT",
  },
  {
    iata: "YYC",
    name: "Calgary International",
    city: "Calgary",
    country: "Canada",
    countryCode: "CA",
    subType: "AIRPORT",
  },
  {
    iata: "YOW",
    name: "Ottawa Macdonald Cartier International",
    city: "Ottawa",
    country: "Canada",
    countryCode: "CA",
    subType: "AIRPORT",
  },
  {
    iata: "YHZ",
    name: "Halifax Stanfield International",
    city: "Halifax",
    country: "Canada",
    countryCode: "CA",
    subType: "AIRPORT",
  },
  {
    iata: "YEG",
    name: "Edmonton International",
    city: "Edmonton",
    country: "Canada",
    countryCode: "CA",
    subType: "AIRPORT",
  },
  {
    iata: "YQB",
    name: "Quebec City Jean Lesage International",
    city: "Quebec City",
    country: "Canada",
    countryCode: "CA",
    subType: "AIRPORT",
  },
  {
    iata: "YWG",
    name: "Winnipeg James Armstrong Richardson International",
    city: "Winnipeg",
    country: "Canada",
    countryCode: "CA",
    subType: "AIRPORT",
  },
  {
    iata: "YYT",
    name: "St Johns International",
    city: "St Johns",
    country: "Canada",
    countryCode: "CA",
    subType: "AIRPORT",
  },
  {
    iata: "MEX",
    name: "Mexico City International",
    city: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    subType: "AIRPORT",
  },
  {
    iata: "CUN",
    name: "Cancun International",
    city: "Cancun",
    country: "Mexico",
    countryCode: "MX",
    subType: "AIRPORT",
  },
  {
    iata: "GDL",
    name: "Guadalajara International",
    city: "Guadalajara",
    country: "Mexico",
    countryCode: "MX",
    subType: "AIRPORT",
  },
  {
    iata: "MTY",
    name: "Monterrey International",
    city: "Monterrey",
    country: "Mexico",
    countryCode: "MX",
    subType: "AIRPORT",
  },
  {
    iata: "TIJ",
    name: "Tijuana International",
    city: "Tijuana",
    country: "Mexico",
    countryCode: "MX",
    subType: "AIRPORT",
  },
  {
    iata: "SJD",
    name: "Los Cabos International",
    city: "San Jose del Cabo",
    country: "Mexico",
    countryCode: "MX",
    subType: "AIRPORT",
  },
  {
    iata: "MID",
    name: "Merida International",
    city: "Merida",
    country: "Mexico",
    countryCode: "MX",
    subType: "AIRPORT",
  },
  {
    iata: "PTY",
    name: "Tocumen International",
    city: "Panama City",
    country: "Panama",
    countryCode: "PA",
    subType: "AIRPORT",
  },
  {
    iata: "SJO",
    name: "Juan Santamaria International",
    city: "San Jose",
    country: "Costa Rica",
    countryCode: "CR",
    subType: "AIRPORT",
  },
  {
    iata: "SAL",
    name: "El Salvador International",
    city: "San Salvador",
    country: "El Salvador",
    countryCode: "SV",
    subType: "AIRPORT",
  },
  {
    iata: "GUA",
    name: "La Aurora International",
    city: "Guatemala City",
    country: "Guatemala",
    countryCode: "GT",
    subType: "AIRPORT",
  },
  {
    iata: "LIR",
    name: "Daniel Oduber International",
    city: "Liberia",
    country: "Costa Rica",
    countryCode: "CR",
    subType: "AIRPORT",
  },
  {
    iata: "PUJ",
    name: "Punta Cana International",
    city: "Punta Cana",
    country: "Dominican Republic",
    countryCode: "DO",
    subType: "AIRPORT",
  },
  {
    iata: "SDQ",
    name: "Las Americas International",
    city: "Santo Domingo",
    country: "Dominican Republic",
    countryCode: "DO",
    subType: "AIRPORT",
  },
  {
    iata: "MBJ",
    name: "Sangster International",
    city: "Montego Bay",
    country: "Jamaica",
    countryCode: "JM",
    subType: "AIRPORT",
  },
  {
    iata: "NAS",
    name: "Lynden Pindling International",
    city: "Nassau",
    country: "Bahamas",
    countryCode: "BS",
    subType: "AIRPORT",
  },
  {
    iata: "BGI",
    name: "Grantley Adams International",
    city: "Bridgetown",
    country: "Barbados",
    countryCode: "BB",
    subType: "AIRPORT",
  },
  {
    iata: "AUA",
    name: "Queen Beatrix International",
    city: "Oranjestad",
    country: "Aruba",
    countryCode: "AW",
    subType: "AIRPORT",
  },
  {
    iata: "STT",
    name: "Cyril E King International",
    city: "St Thomas",
    country: "United States Virgin Islands",
    countryCode: "VI",
    subType: "AIRPORT",
  },
  {
    iata: "STX",
    name: "Henry E Rohlsen",
    city: "St Croix",
    country: "United States Virgin Islands",
    countryCode: "VI",
    subType: "AIRPORT",
  },
  {
    iata: "BOG",
    name: "El Dorado International",
    city: "Bogota",
    country: "Colombia",
    countryCode: "CO",
    subType: "AIRPORT",
  },
  {
    iata: "LIM",
    name: "Jorge Chavez International",
    city: "Lima",
    country: "Peru",
    countryCode: "PE",
    subType: "AIRPORT",
  },
  {
    iata: "SCL",
    name: "Arturo Merino Benitez International",
    city: "Santiago",
    country: "Chile",
    countryCode: "CL",
    subType: "AIRPORT",
  },
  {
    iata: "EZE",
    name: "Ministro Pistarini International",
    city: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    subType: "AIRPORT",
  },
  {
    iata: "AEP",
    name: "Jorge Newbery",
    city: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    subType: "AIRPORT",
  },
  {
    iata: "GRU",
    name: "Sao Paulo Guarulhos International",
    city: "Sao Paulo",
    country: "Brazil",
    countryCode: "BR",
    subType: "AIRPORT",
  },
  {
    iata: "GIG",
    name: "Rio de Janeiro Galeao International",
    city: "Rio de Janeiro",
    country: "Brazil",
    countryCode: "BR",
    subType: "AIRPORT",
  },
  {
    iata: "BSB",
    name: "Brasilia International",
    city: "Brasilia",
    country: "Brazil",
    countryCode: "BR",
    subType: "AIRPORT",
  },
  {
    iata: "CNF",
    name: "Belo Horizonte Tancredo Neves International",
    city: "Belo Horizonte",
    country: "Brazil",
    countryCode: "BR",
    subType: "AIRPORT",
  },
  {
    iata: "SSA",
    name: "Salvador Deputado Luis Eduardo Magalhaes International",
    city: "Salvador",
    country: "Brazil",
    countryCode: "BR",
    subType: "AIRPORT",
  },
  {
    iata: "REC",
    name: "Recife Guararapes International",
    city: "Recife",
    country: "Brazil",
    countryCode: "BR",
    subType: "AIRPORT",
  },
  {
    iata: "FOR",
    name: "Fortaleza Pinto Martins International",
    city: "Fortaleza",
    country: "Brazil",
    countryCode: "BR",
    subType: "AIRPORT",
  },
  {
    iata: "POA",
    name: "Porto Alegre Salgado Filho International",
    city: "Porto Alegre",
    country: "Brazil",
    countryCode: "BR",
    subType: "AIRPORT",
  },
  {
    iata: "UIO",
    name: "Mariscal Sucre International",
    city: "Quito",
    country: "Ecuador",
    countryCode: "EC",
    subType: "AIRPORT",
  },
  {
    iata: "GYE",
    name: "Jose Joaquin de Olmedo International",
    city: "Guayaquil",
    country: "Ecuador",
    countryCode: "EC",
    subType: "AIRPORT",
  },
  {
    iata: "MVD",
    name: "Carrasco International",
    city: "Montevideo",
    country: "Uruguay",
    countryCode: "UY",
    subType: "AIRPORT",
  },
  {
    iata: "ASU",
    name: "Silvio Pettirossi International",
    city: "Asuncion",
    country: "Paraguay",
    countryCode: "PY",
    subType: "AIRPORT",
  },
  {
    iata: "LPB",
    name: "El Alto International",
    city: "La Paz",
    country: "Bolivia",
    countryCode: "BO",
    subType: "AIRPORT",
  },
  {
    iata: "LHR",
    name: "Heathrow",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    subType: "AIRPORT",
  },
  {
    iata: "LGW",
    name: "Gatwick",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    subType: "AIRPORT",
  },
  {
    iata: "STN",
    name: "Stansted",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    subType: "AIRPORT",
  },
  {
    iata: "MAN",
    name: "Manchester",
    city: "Manchester",
    country: "United Kingdom",
    countryCode: "GB",
    subType: "AIRPORT",
  },
  {
    iata: "BHX",
    name: "Birmingham",
    city: "Birmingham",
    country: "United Kingdom",
    countryCode: "GB",
    subType: "AIRPORT",
  },
  {
    iata: "EDI",
    name: "Edinburgh",
    city: "Edinburgh",
    country: "United Kingdom",
    countryCode: "GB",
    subType: "AIRPORT",
  },
  {
    iata: "GLA",
    name: "Glasgow International",
    city: "Glasgow",
    country: "United Kingdom",
    countryCode: "GB",
    subType: "AIRPORT",
  },
  {
    iata: "DUB",
    name: "Dublin",
    city: "Dublin",
    country: "Ireland",
    countryCode: "IE",
    subType: "AIRPORT",
  },
  {
    iata: "ORK",
    name: "Cork",
    city: "Cork",
    country: "Ireland",
    countryCode: "IE",
    subType: "AIRPORT",
  },
  {
    iata: "CDG",
    name: "Charles de Gaulle",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    subType: "AIRPORT",
  },
  {
    iata: "ORY",
    name: "Orly",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    subType: "AIRPORT",
  },
  {
    iata: "NCE",
    name: "Nice Cote d Azur",
    city: "Nice",
    country: "France",
    countryCode: "FR",
    subType: "AIRPORT",
  },
  {
    iata: "LYS",
    name: "Lyon Saint Exupery",
    city: "Lyon",
    country: "France",
    countryCode: "FR",
    subType: "AIRPORT",
  },
  {
    iata: "MRS",
    name: "Marseille Provence",
    city: "Marseille",
    country: "France",
    countryCode: "FR",
    subType: "AIRPORT",
  },
  {
    iata: "AMS",
    name: "Schiphol",
    city: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    subType: "AIRPORT",
  },
  {
    iata: "BRU",
    name: "Brussels",
    city: "Brussels",
    country: "Belgium",
    countryCode: "BE",
    subType: "AIRPORT",
  },
  {
    iata: "CRL",
    name: "Brussels South Charleroi",
    city: "Charleroi",
    country: "Belgium",
    countryCode: "BE",
    subType: "AIRPORT",
  },
  {
    iata: "RTM",
    name: "Rotterdam The Hague",
    city: "Rotterdam",
    country: "Netherlands",
    countryCode: "NL",
    subType: "AIRPORT",
  },
  {
    iata: "FRA",
    name: "Frankfurt",
    city: "Frankfurt",
    country: "Germany",
    countryCode: "DE",
    subType: "AIRPORT",
  },
  {
    iata: "MUC",
    name: "Munich",
    city: "Munich",
    country: "Germany",
    countryCode: "DE",
    subType: "AIRPORT",
  },
  {
    iata: "BER",
    name: "Berlin Brandenburg",
    city: "Berlin",
    country: "Germany",
    countryCode: "DE",
    subType: "AIRPORT",
  },
  {
    iata: "DUS",
    name: "Dusseldorf",
    city: "Dusseldorf",
    country: "Germany",
    countryCode: "DE",
    subType: "AIRPORT",
  },
  {
    iata: "HAM",
    name: "Hamburg",
    city: "Hamburg",
    country: "Germany",
    countryCode: "DE",
    subType: "AIRPORT",
  },
  {
    iata: "CGN",
    name: "Cologne Bonn",
    city: "Cologne",
    country: "Germany",
    countryCode: "DE",
    subType: "AIRPORT",
  },
  {
    iata: "ZRH",
    name: "Zurich",
    city: "Zurich",
    country: "Switzerland",
    countryCode: "CH",
    subType: "AIRPORT",
  },
  {
    iata: "GVA",
    name: "Geneva",
    city: "Geneva",
    country: "Switzerland",
    countryCode: "CH",
    subType: "AIRPORT",
  },
  {
    iata: "VIE",
    name: "Vienna",
    city: "Vienna",
    country: "Austria",
    countryCode: "AT",
    subType: "AIRPORT",
  },
  {
    iata: "MAD",
    name: "Adolfo Suarez Madrid Barajas",
    city: "Madrid",
    country: "Spain",
    countryCode: "ES",
    subType: "AIRPORT",
  },
  {
    iata: "BCN",
    name: "Barcelona El Prat",
    city: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    subType: "AIRPORT",
  },
  {
    iata: "VLC",
    name: "Valencia",
    city: "Valencia",
    country: "Spain",
    countryCode: "ES",
    subType: "AIRPORT",
  },
  {
    iata: "PMI",
    name: "Palma de Mallorca",
    city: "Palma",
    country: "Spain",
    countryCode: "ES",
    subType: "AIRPORT",
  },
  {
    iata: "LIS",
    name: "Lisbon Humberto Delgado",
    city: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    subType: "AIRPORT",
  },
  {
    iata: "OPO",
    name: "Porto",
    city: "Porto",
    country: "Portugal",
    countryCode: "PT",
    subType: "AIRPORT",
  },
  {
    iata: "FAO",
    name: "Faro",
    city: "Faro",
    country: "Portugal",
    countryCode: "PT",
    subType: "AIRPORT",
  },
  {
    iata: "FCO",
    name: "Rome Fiumicino",
    city: "Rome",
    country: "Italy",
    countryCode: "IT",
    subType: "AIRPORT",
  },
  {
    iata: "MXP",
    name: "Milan Malpensa",
    city: "Milan",
    country: "Italy",
    countryCode: "IT",
    subType: "AIRPORT",
  },
  {
    iata: "LIN",
    name: "Milan Linate",
    city: "Milan",
    country: "Italy",
    countryCode: "IT",
    subType: "AIRPORT",
  },
  {
    iata: "VCE",
    name: "Venice Marco Polo",
    city: "Venice",
    country: "Italy",
    countryCode: "IT",
    subType: "AIRPORT",
  },
  {
    iata: "BLQ",
    name: "Bologna Guglielmo Marconi",
    city: "Bologna",
    country: "Italy",
    countryCode: "IT",
    subType: "AIRPORT",
  },
  {
    iata: "NAP",
    name: "Naples International",
    city: "Naples",
    country: "Italy",
    countryCode: "IT",
    subType: "AIRPORT",
  },
  {
    iata: "ARN",
    name: "Stockholm Arlanda",
    city: "Stockholm",
    country: "Sweden",
    countryCode: "SE",
    subType: "AIRPORT",
  },
  {
    iata: "OSL",
    name: "Oslo Gardermoen",
    city: "Oslo",
    country: "Norway",
    countryCode: "NO",
    subType: "AIRPORT",
  },
  {
    iata: "CPH",
    name: "Copenhagen",
    city: "Copenhagen",
    country: "Denmark",
    countryCode: "DK",
    subType: "AIRPORT",
  },
  {
    iata: "HEL",
    name: "Helsinki",
    city: "Helsinki",
    country: "Finland",
    countryCode: "FI",
    subType: "AIRPORT",
  },
  {
    iata: "GOT",
    name: "Gothenburg Landvetter",
    city: "Gothenburg",
    country: "Sweden",
    countryCode: "SE",
    subType: "AIRPORT",
  },
  {
    iata: "BGO",
    name: "Bergen Flesland",
    city: "Bergen",
    country: "Norway",
    countryCode: "NO",
    subType: "AIRPORT",
  },
  {
    iata: "PRG",
    name: "Prague Vaclav Havel",
    city: "Prague",
    country: "Czech Republic",
    countryCode: "CZ",
    subType: "AIRPORT",
  },
  {
    iata: "BUD",
    name: "Budapest Ferenc Liszt",
    city: "Budapest",
    country: "Hungary",
    countryCode: "HU",
    subType: "AIRPORT",
  },
  {
    iata: "WAW",
    name: "Warsaw Chopin",
    city: "Warsaw",
    country: "Poland",
    countryCode: "PL",
    subType: "AIRPORT",
  },
  {
    iata: "KRK",
    name: "Krakow John Paul II",
    city: "Krakow",
    country: "Poland",
    countryCode: "PL",
    subType: "AIRPORT",
  },
  {
    iata: "OTP",
    name: "Henri Coanda",
    city: "Bucharest",
    country: "Romania",
    countryCode: "RO",
    subType: "AIRPORT",
  },
  {
    iata: "SOF",
    name: "Sofia",
    city: "Sofia",
    country: "Bulgaria",
    countryCode: "BG",
    subType: "AIRPORT",
  },
  {
    iata: "BEG",
    name: "Belgrade Nikola Tesla",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    subType: "AIRPORT",
  },
  {
    iata: "ZAG",
    name: "Zagreb",
    city: "Zagreb",
    country: "Croatia",
    countryCode: "HR",
    subType: "AIRPORT",
  },
  {
    iata: "LJU",
    name: "Ljubljana Joze Pucnik",
    city: "Ljubljana",
    country: "Slovenia",
    countryCode: "SI",
    subType: "AIRPORT",
  },
  {
    iata: "RIX",
    name: "Riga",
    city: "Riga",
    country: "Latvia",
    countryCode: "LV",
    subType: "AIRPORT",
  },
  {
    iata: "VNO",
    name: "Vilnius",
    city: "Vilnius",
    country: "Lithuania",
    countryCode: "LT",
    subType: "AIRPORT",
  },
  {
    iata: "TLL",
    name: "Tallinn",
    city: "Tallinn",
    country: "Estonia",
    countryCode: "EE",
    subType: "AIRPORT",
  },
  {
    iata: "KEF",
    name: "Keflavik International",
    city: "Reykjavik",
    country: "Iceland",
    countryCode: "IS",
    subType: "AIRPORT",
  },
  {
    iata: "ATH",
    name: "Athens International",
    city: "Athens",
    country: "Greece",
    countryCode: "GR",
    subType: "AIRPORT",
  },
  {
    iata: "IST",
    name: "Istanbul",
    city: "Istanbul",
    country: "Turkey",
    countryCode: "TR",
    subType: "AIRPORT",
  },
  {
    iata: "SAW",
    name: "Sabiha Gokcen",
    city: "Istanbul",
    country: "Turkey",
    countryCode: "TR",
    subType: "AIRPORT",
  },
  {
    iata: "TLV",
    name: "Ben Gurion",
    city: "Tel Aviv",
    country: "Israel",
    countryCode: "IL",
    subType: "AIRPORT",
  },
  {
    iata: "LCA",
    name: "Larnaca International",
    city: "Larnaca",
    country: "Cyprus",
    countryCode: "CY",
    subType: "AIRPORT",
  },
  {
    iata: "MLA",
    name: "Malta International",
    city: "Malta",
    country: "Malta",
    countryCode: "MT",
    subType: "AIRPORT",
  },
  {
    iata: "DXB",
    name: "Dubai International",
    city: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    subType: "AIRPORT",
  },
  {
    iata: "AUH",
    name: "Abu Dhabi International",
    city: "Abu Dhabi",
    country: "United Arab Emirates",
    countryCode: "AE",
    subType: "AIRPORT",
  },
  {
    iata: "DOH",
    name: "Hamad International",
    city: "Doha",
    country: "Qatar",
    countryCode: "QA",
    subType: "AIRPORT",
  },
  {
    iata: "KWI",
    name: "Kuwait International",
    city: "Kuwait City",
    country: "Kuwait",
    countryCode: "KW",
    subType: "AIRPORT",
  },
  {
    iata: "RUH",
    name: "King Khalid International",
    city: "Riyadh",
    country: "Saudi Arabia",
    countryCode: "SA",
    subType: "AIRPORT",
  },
  {
    iata: "JED",
    name: "King Abdulaziz International",
    city: "Jeddah",
    country: "Saudi Arabia",
    countryCode: "SA",
    subType: "AIRPORT",
  },
  {
    iata: "MCT",
    name: "Muscat International",
    city: "Muscat",
    country: "Oman",
    countryCode: "OM",
    subType: "AIRPORT",
  },
  {
    iata: "BAH",
    name: "Bahrain International",
    city: "Manama",
    country: "Bahrain",
    countryCode: "BH",
    subType: "AIRPORT",
  },
  {
    iata: "AMM",
    name: "Queen Alia International",
    city: "Amman",
    country: "Jordan",
    countryCode: "JO",
    subType: "AIRPORT",
  },
  {
    iata: "JNB",
    name: "OR Tambo International",
    city: "Johannesburg",
    country: "South Africa",
    countryCode: "ZA",
    subType: "AIRPORT",
  },
  {
    iata: "CPT",
    name: "Cape Town International",
    city: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    subType: "AIRPORT",
  },
  {
    iata: "CAI",
    name: "Cairo International",
    city: "Cairo",
    country: "Egypt",
    countryCode: "EG",
    subType: "AIRPORT",
  },
  {
    iata: "ADD",
    name: "Addis Ababa Bole International",
    city: "Addis Ababa",
    country: "Ethiopia",
    countryCode: "ET",
    subType: "AIRPORT",
  },
  {
    iata: "NBO",
    name: "Jomo Kenyatta International",
    city: "Nairobi",
    country: "Kenya",
    countryCode: "KE",
    subType: "AIRPORT",
  },
  {
    iata: "HND",
    name: "Tokyo Haneda",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    subType: "AIRPORT",
  },
  {
    iata: "NRT",
    name: "Tokyo Narita",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    subType: "AIRPORT",
  },
  {
    iata: "KIX",
    name: "Kansai International",
    city: "Osaka",
    country: "Japan",
    countryCode: "JP",
    subType: "AIRPORT",
  },
  {
    iata: "ICN",
    name: "Incheon International",
    city: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    subType: "AIRPORT",
  },
  {
    iata: "GMP",
    name: "Gimpo International",
    city: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    subType: "AIRPORT",
  },
  {
    iata: "HKG",
    name: "Hong Kong International",
    city: "Hong Kong",
    country: "Hong Kong",
    countryCode: "HK",
    subType: "AIRPORT",
  },
  {
    iata: "TPE",
    name: "Taiwan Taoyuan International",
    city: "Taipei",
    country: "Taiwan",
    countryCode: "TW",
    subType: "AIRPORT",
  },
  {
    iata: "PVG",
    name: "Shanghai Pudong",
    city: "Shanghai",
    country: "China",
    countryCode: "CN",
    subType: "AIRPORT",
  },
  {
    iata: "SHA",
    name: "Shanghai Hongqiao",
    city: "Shanghai",
    country: "China",
    countryCode: "CN",
    subType: "AIRPORT",
  },
  {
    iata: "PEK",
    name: "Beijing Capital",
    city: "Beijing",
    country: "China",
    countryCode: "CN",
    subType: "AIRPORT",
  },
  {
    iata: "PKX",
    name: "Beijing Daxing",
    city: "Beijing",
    country: "China",
    countryCode: "CN",
    subType: "AIRPORT",
  },
  {
    iata: "CAN",
    name: "Guangzhou Baiyun",
    city: "Guangzhou",
    country: "China",
    countryCode: "CN",
    subType: "AIRPORT",
  },
  {
    iata: "SZX",
    name: "Shenzhen Baoan",
    city: "Shenzhen",
    country: "China",
    countryCode: "CN",
    subType: "AIRPORT",
  },
  {
    iata: "SIN",
    name: "Singapore Changi",
    city: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    subType: "AIRPORT",
  },
  {
    iata: "KUL",
    name: "Kuala Lumpur International",
    city: "Kuala Lumpur",
    country: "Malaysia",
    countryCode: "MY",
    subType: "AIRPORT",
  },
  {
    iata: "BKK",
    name: "Suvarnabhumi",
    city: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    subType: "AIRPORT",
  },
  {
    iata: "DMK",
    name: "Don Mueang",
    city: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    subType: "AIRPORT",
  },
  {
    iata: "CGK",
    name: "Soekarno Hatta",
    city: "Jakarta",
    country: "Indonesia",
    countryCode: "ID",
    subType: "AIRPORT",
  },
  {
    iata: "DPS",
    name: "Ngurah Rai",
    city: "Denpasar",
    country: "Indonesia",
    countryCode: "ID",
    subType: "AIRPORT",
  },
  {
    iata: "MNL",
    name: "Ninoy Aquino International",
    city: "Manila",
    country: "Philippines",
    countryCode: "PH",
    subType: "AIRPORT",
  },
  {
    iata: "CEB",
    name: "Mactan Cebu International",
    city: "Cebu",
    country: "Philippines",
    countryCode: "PH",
    subType: "AIRPORT",
  },
  {
    iata: "HAN",
    name: "Noi Bai",
    city: "Hanoi",
    country: "Vietnam",
    countryCode: "VN",
    subType: "AIRPORT",
  },
  {
    iata: "SGN",
    name: "Tan Son Nhat",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    countryCode: "VN",
    subType: "AIRPORT",
  },
  {
    iata: "SYD",
    name: "Sydney Kingsford Smith",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    subType: "AIRPORT",
  },
  {
    iata: "MEL",
    name: "Melbourne",
    city: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    subType: "AIRPORT",
  },
  {
    iata: "BNE",
    name: "Brisbane",
    city: "Brisbane",
    country: "Australia",
    countryCode: "AU",
    subType: "AIRPORT",
  },
  {
    iata: "PER",
    name: "Perth",
    city: "Perth",
    country: "Australia",
    countryCode: "AU",
    subType: "AIRPORT",
  },
  {
    iata: "ADL",
    name: "Adelaide",
    city: "Adelaide",
    country: "Australia",
    countryCode: "AU",
    subType: "AIRPORT",
  },
  {
    iata: "AKL",
    name: "Auckland International",
    city: "Auckland",
    country: "New Zealand",
    countryCode: "NZ",
    subType: "AIRPORT",
  },
  {
    iata: "WLG",
    name: "Wellington International",
    city: "Wellington",
    country: "New Zealand",
    countryCode: "NZ",
    subType: "AIRPORT",
  },
  {
    iata: "CHC",
    name: "Christchurch International",
    city: "Christchurch",
    country: "New Zealand",
    countryCode: "NZ",
    subType: "AIRPORT",
  },
];

const maxResults = 12;

export function findAirportByIata(iata: string): LocationOption | undefined {
  const code = iata.trim().toUpperCase();
  if (!code) {
    return undefined;
  }

  return AIRPORTS.find((airport) => airport.iata === code);
}

export function searchAirports(query: string): LocationOption[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) {
    return [];
  }

  const scored = AIRPORTS.map((airport) => {
    const haystack = `${airport.iata} ${airport.city} ${airport.name} ${airport.country}`.toLowerCase();

    let score = 0;
    if (airport.iata.toLowerCase().startsWith(normalized)) {
      score += 4;
    }
    if (airport.city.toLowerCase().startsWith(normalized)) {
      score += 3;
    }
    if (airport.name.toLowerCase().startsWith(normalized)) {
      score += 2;
    }
    if (haystack.includes(normalized)) {
      score += 1;
    }

    return { airport, score };
  }).filter((item) => item.score > 0);

  return scored
    .sort((a, b) => b.score - a.score)
    .slice(0, maxResults)
    .map((item) => item.airport);
}

